version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: tradingplatform
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - trading-network

  trading-app:
    build: .
    container_name: trading-platform
    restart: always
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - trading-network

volumes:
  mysql_data:

networks:
  trading-network:
    driver: bridge
